version: '3'

services:
  php-fpm:
    build: php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/html/app/
    restart: always
    environment:
      APP_ENV:
      APP_DEBUG:
      APP_KEY:
      APP_TIMEZONE:
      LOG_CHANNEL:
      LOG_SLACK_WEBHOOK_URL:
      DB_CONNECTION:
      DB_HOST:
      DB_PORT: 
      DB_DATABASE:
      DB_USERNAME:
      DB_PASSWORD:
      CACHE_DRIVER:
      QUEUE_DRIVER:      
    networks:
      - backend
    links:
      - db

  nginx:
    build: nginx
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html/app/
    restart: always       
    links:
      - php-fpm
    networks:
      - backend


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker_user123
      POSTGRES_USER: postgres
      POSTGRES_DB: genesis
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pg-data:

networks:
  backend:
    driver: bridge
 

